# Basic configuration for LightningLens
project:
  name: 'LightningLens'
  version: '0.1.0'

# Data collection settings
data_collection:
  timeframe_hours: 24
  batch_size: 32

# Model parameters
model:
  hidden_size: 64
  num_layers: 2
  dropout: 0.2
  sequence_length: 24

# Training parameters
training:
  learning_rate: 0.001
  batch_size: 32
  epochs: 50
  validation_split: 0.2

# Paths
paths:
  raw_data: 'data/raw'
  processed_data: 'data/processed'
  models: 'data/models'
