services:
  lnd-alice:
    volumes:
      - ./volumes/alice:/root/.lnd
    ports:
      - '10009:10009' # Expose to host

  lnd-bob:
    volumes:
      - ./volumes/bob:/root/.lnd
    ports:
      - '10010:10009' # Note different host port
